version: '3'
services:
  react-app:
    build:
    #Provide the path where you want docker-compose to find the Dockerfile
      context: .
    #Dockerfile name
      dockerfile: Dockerfile.dev
    #env configuration for windows
    environment:
      env_file: .env
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
    #folder in the docker container which you donot want to map
      - /app/node_modules
    #folder in your project which you would want to map
      - .:/app
  tests:
    build:
    #Provide the path where you want docker-compose to find the Dockerfile
      context: .
    #Dockerfile name
      dockerfile: Dockerfile.dev
    #env configuration for windows
    environment:
      env_file: .env
      NODE_ENV: development
    volumes:
    #folder in the docker container which you donot want to map
      - /app/node_modules
    #folder in your project which you would want to map
      - .:/app
    #Command to execute tests
    command: ["npm", "run", "test"]